//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""GroundMove"",
            ""id"": ""eaecacda-db4d-4f22-8f7e-2a0e1cf3f0c2"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""1c6f0585-fbd0-4e24-a038-254a7b540b02"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""d21e643f-0386-42b5-b13a-d8a42dc7c439"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""Scale(factor=0.001)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""27861bd6-181d-4137-be3d-bbe507a9459d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DashJump"",
                    ""type"": ""Button"",
                    ""id"": ""96b09658-b587-40e3-aebb-928b460df9ed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""51f25f5b-1735-4d9c-b77c-a2240e22fdda"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L1"",
                    ""type"": ""Button"",
                    ""id"": ""243bdd3b-8132-497b-b19f-fb72f47778f9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R1"",
                    ""type"": ""Button"",
                    ""id"": ""19fb52ff-ee50-47ab-9c75-1ffbf64890e1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveCursor"",
                    ""type"": ""Value"",
                    ""id"": ""718bf39c-4d42-4205-954e-278f36d2e362"",
                    ""expectedControlType"": ""Dpad"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Lockon"",
                    ""type"": ""Value"",
                    ""id"": ""faaaaffe-9971-4867-b28b-b96f363dfbb3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sword"",
                    ""type"": ""Button"",
                    ""id"": ""288d1443-8636-4228-a49f-e200d5a839a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""993b2ee9-a319-421c-a407-df601f9d3669"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.5)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Button"",
                    ""id"": ""a950547d-d71b-43cd-a8ca-7fe86496cb0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""909126fb-a505-4b60-9114-340c2f1b4ff0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f279d315-f118-46f0-a844-589b305a1105"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7cf3c08e-1ce5-4a6e-985d-c4ac82418a75"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0875df92-377f-45b5-b480-df24584721d7"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""242ac25c-9efd-4c1a-afdb-e358a5423f83"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""25f76430-8aaf-460a-bb4b-dd0a1b8534ba"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""beda6885-a27e-4c24-9622-e3e71d653bde"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0.1,y=0.25)"",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""942cd32b-3fbe-403e-9189-18e42a1204d5"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9336e21c-278f-4958-8f8a-028aaa0847a1"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aed57cb4-b4c4-42c8-a8c6-296e6e6dfc34"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c8d1c6c-a6a4-4f11-9cdb-50c1a92f78f9"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccb2e29a-aa73-4742-8445-1ae29ccabcc6"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61192204-a16d-4f2c-bbdc-dc4776311673"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e159a0cd-e949-4339-9abf-89e18ae64978"",
                    ""path"": ""<Keyboard>/capsLock"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66a6bd6d-1572-44b9-a661-a8198961eb99"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a266d4cd-4082-41f6-ac5e-c3bffcaeb7c0"",
                    ""path"": ""<Keyboard>/capsLock"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""369e6833-3918-4b72-9ab5-e6b0ae3cc260"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c258018d-afd6-4283-92cd-b880adb1e4ce"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eba092c0-b713-48be-b79c-c750a0d1e419"",
                    ""path"": ""<XInputController>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lockon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ceb36fc0-6a54-4673-8356-add441d7eef9"",
                    ""path"": ""<Keyboard>/capsLock"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lockon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc781913-5a7c-4809-a095-f7afc888c738"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DashJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""caae7b1b-ef2d-434d-ab01-8cd2d5b5147b"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DashJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35c4fa62-fcc8-4108-bd3a-6d06fea54b91"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DashJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2572e4c1-4cde-4e71-999b-b60ed319cf71"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sword"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff309861-78eb-4b7a-aece-fff2d4fe823a"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sword"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""337e0e3c-24f5-4cfe-bf3c-6fb6fdf21826"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c777055-3e93-44df-be39-f7c5ac963872"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a0187fe-cb8f-41dd-bb4d-6a49e0fc9b9e"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec8acf1d-5db9-4f2d-801a-6b92b55af5b0"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""WaterMove"",
            ""id"": ""e8a865ae-1c37-4c53-8eca-aea200a30cd4"",
            ""actions"": [
                {
                    ""name"": ""Turn"",
                    ""type"": ""Value"",
                    ""id"": ""5074b856-ae64-4bb0-8dd0-6440f4d54ecc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""ba34b786-73a5-4443-bee8-6d06b0c0b9cf"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""ScaleVector2(x=0.001)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Accelerate"",
                    ""type"": ""Button"",
                    ""id"": ""b52a9ad6-0256-4309-8481-cb5874900d4c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rise"",
                    ""type"": ""Value"",
                    ""id"": ""3e26f876-c614-48ac-9f7e-5c5d734c2dc6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fall"",
                    ""type"": ""Value"",
                    ""id"": ""9acae49b-d052-404f-849b-cbd8efe96c47"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Boost"",
                    ""type"": ""Button"",
                    ""id"": ""5aa6692b-a2ea-41a2-8d02-2302894a910a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""ff9e56f7-9aee-41e6-9494-25b2886cb61d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.5)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""7ca3729b-2faa-4698-9c19-ee9ca1c84b33"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""8a0df67a-6df2-43a3-bfc6-7188ed05eb32"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveCursor"",
                    ""type"": ""Value"",
                    ""id"": ""09814fe0-3f76-4fd9-b7f9-fca65b0cec8f"",
                    ""expectedControlType"": ""Dpad"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Lockon"",
                    ""type"": ""Button"",
                    ""id"": ""75bd9bdc-a5ab-4cfc-92cc-c21bbd0d2d66"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Throttle"",
                    ""type"": ""Button"",
                    ""id"": ""5387ddca-bb47-418f-8017-d003d3952ead"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d00762e8-fd97-4ac5-a13d-79ed294962c0"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""993b1fcf-2ac1-4acf-96ee-c786ffc3b599"",
                    ""path"": ""<SwitchProControllerHID>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd6793bd-7fe4-4c96-81bf-1781facf7682"",
                    ""path"": ""<WebGLGamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7feba8a6-8f2d-4dd3-a409-53e171866a59"",
                    ""path"": ""<XboxOneGampadiOS>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b07072a4-0569-477a-b89c-931d8614bc22"",
                    ""path"": ""<DualShockGamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""454a9517-051d-45bc-a942-e8fbce37fa6c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b13555b9-754a-4814-ad9d-c5426336514f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ca1e6c23-4e28-486f-8aa9-48f6e1f98edb"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""08e599a3-3039-459f-b4eb-d5ca0be53962"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""18774323-d750-4f14-9b8c-8e0301d7ce5a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2be6137a-6a06-4663-a9d8-a885b25cbdb5"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16df3b78-745d-46c0-8b4e-3a433b7afc70"",
                    ""path"": ""<SwitchProControllerHID>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e2ec9e4-6223-41f4-bc3a-259861236434"",
                    ""path"": ""<XboxOneGampadiOS>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1671a650-cad2-4196-8b58-5118e2234ba8"",
                    ""path"": ""<WebGLGamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96d0d03c-b9ec-4617-97e2-b75e7434eab2"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0.05)"",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0419296f-8780-4c38-90f9-58e0497f0643"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc44c325-5e85-4903-8d1f-f5655ffa3442"",
                    ""path"": ""<SwitchProControllerHID>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d0bd16c-f006-4369-94b5-b2207cca86cb"",
                    ""path"": ""<WebGLGamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e70b739-eb9d-4224-b15b-95fc5e739b1a"",
                    ""path"": ""<DualShockGamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abc8c5d6-17e2-4d8b-8188-86a58ebfd05a"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4293c12-17c0-4447-a805-533e4fbc5ada"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97f94600-b1c6-451a-b4a2-51c005a73dbe"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7bdecc8-7b62-4a22-9cf0-cfb2d45c208c"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rise"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""33214363-5399-4028-b96a-4708d683742e"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rise"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""ed36d71f-0da9-420e-bc1a-d8c145c47def"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rise"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""c934f068-f075-4ca6-a70b-6225d1adb2e7"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rise"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3a3e1c61-977e-40f0-8e32-2d9fa01d3204"",
                    ""path"": ""<DualShockGamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rise"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87bd8302-e382-44d5-b955-353a90f85081"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67bc4e62-46f8-4ec0-bf6b-e24fa4af859c"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""63f5a52f-819d-4c83-86ad-0e4991778c02"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fall"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""1d70bd74-82b9-4c65-a6c0-d2f9f2647d0c"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""efaaa244-e988-4697-b62c-bfa456700c7f"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""96807476-721e-49cb-82bb-e0dc0f76c2de"",
                    ""path"": ""<DualShockGamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fall"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43943971-88b7-4787-85a3-8ebd37eb5e54"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""235bc60b-97a5-4dc3-a8c3-b8c8ff72ea8c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""f466a388-1f8d-4e5d-b3bc-e2952dcbd9ee"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis mouse"",
                    ""id"": ""80e624a9-3740-467d-8a9c-826581675e94"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""f0975b0e-e104-4c4c-b28b-75c8cc5746b3"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""e3db2121-fe48-4590-8471-41f9e804d602"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button With One Modifier"",
                    ""id"": ""dcc8aa6a-e087-4868-84d9-bd92a5470f93"",
                    ""path"": ""ButtonWithOneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Modifier"",
                    ""id"": ""34a7d0b1-8707-4235-976c-f337333c17e4"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Button"",
                    ""id"": ""088d7d0e-427a-4fbb-87e5-02e87bf811f5"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""21395db8-4ff6-4a60-8a01-5f09176d4ea6"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65495893-6dd6-42aa-973e-7826bb8bc639"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""778181e9-6f43-4c93-a82e-e2d75d507874"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ca0d8c81-1d98-4c81-99e3-a4c7169174ef"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""74300a4a-5073-469d-aea5-3aec97ae230f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e56e1922-9369-4a64-a4c3-ffac5d82de09"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""93e1003e-7e2f-4dd3-8770-39210032fffd"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""75b8496e-6b70-430b-b33b-490d231c460e"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d185fa2-1984-4739-9b37-d637ee910e98"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3169c95-3814-465d-8acf-133e8dc59bb9"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""420b27a6-6ccc-497f-b83f-770c5d8d2429"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32d2ffe4-8a22-4d15-92f2-88a7e54f4c96"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95c9ac10-58fa-445f-9ad6-3130e73bec46"",
                    ""path"": ""<XInputController>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lockon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38daf438-48f9-4e11-8191-42c59f728380"",
                    ""path"": ""<Keyboard>/capsLock"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lockon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f8959fd-3bed-4daf-9e72-ab9d06401a91"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf24c8b0-6f49-4447-9456-875fdac12702"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd4a8db7-217d-4fb6-98c8-ddb02965e213"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""LedgeGrab"",
            ""id"": ""44d78c56-b3c2-40ec-9dac-587a01636be4"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""e91fb130-0c3e-4604-a969-be84a560ae55"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.5)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""272f5569-7af5-4720-9bd6-a899d2da8164"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9bb9b183-158c-4451-b5fe-28a0889c54da"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d99ad111-891a-4a5a-8f42-ce03ddaa1534"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""708d2d53-eb0c-4d6f-bb94-57598a728dc4"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""28d9fa3a-2f1b-4ee8-8b3c-ac017f25c7b0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""833b6e01-fe09-4adf-b01a-62cb5e70295e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1a81dab1-524c-481f-a213-3ddca1d9d4e0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1a5db7b3-0d33-4e9c-a885-917becd33247"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5fbcd7bc-a6e2-4865-9777-1d020840e7d5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""fd6c6dd3-9cbb-4245-9f26-e3a942f8d79e"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GroundMove
        m_GroundMove = asset.FindActionMap("GroundMove", throwIfNotFound: true);
        m_GroundMove_Move = m_GroundMove.FindAction("Move", throwIfNotFound: true);
        m_GroundMove_Rotate = m_GroundMove.FindAction("Rotate", throwIfNotFound: true);
        m_GroundMove_Jump = m_GroundMove.FindAction("Jump", throwIfNotFound: true);
        m_GroundMove_DashJump = m_GroundMove.FindAction("DashJump", throwIfNotFound: true);
        m_GroundMove_Dash = m_GroundMove.FindAction("Dash", throwIfNotFound: true);
        m_GroundMove_L1 = m_GroundMove.FindAction("L1", throwIfNotFound: true);
        m_GroundMove_R1 = m_GroundMove.FindAction("R1", throwIfNotFound: true);
        m_GroundMove_MoveCursor = m_GroundMove.FindAction("MoveCursor", throwIfNotFound: true);
        m_GroundMove_Lockon = m_GroundMove.FindAction("Lockon", throwIfNotFound: true);
        m_GroundMove_Sword = m_GroundMove.FindAction("Sword", throwIfNotFound: true);
        m_GroundMove_Attack = m_GroundMove.FindAction("Attack", throwIfNotFound: true);
        m_GroundMove_Aim = m_GroundMove.FindAction("Aim", throwIfNotFound: true);
        // WaterMove
        m_WaterMove = asset.FindActionMap("WaterMove", throwIfNotFound: true);
        m_WaterMove_Turn = m_WaterMove.FindAction("Turn", throwIfNotFound: true);
        m_WaterMove_Rotate = m_WaterMove.FindAction("Rotate", throwIfNotFound: true);
        m_WaterMove_Accelerate = m_WaterMove.FindAction("Accelerate", throwIfNotFound: true);
        m_WaterMove_Rise = m_WaterMove.FindAction("Rise", throwIfNotFound: true);
        m_WaterMove_Fall = m_WaterMove.FindAction("Fall", throwIfNotFound: true);
        m_WaterMove_Boost = m_WaterMove.FindAction("Boost", throwIfNotFound: true);
        m_WaterMove_Attack = m_WaterMove.FindAction("Attack", throwIfNotFound: true);
        m_WaterMove_Jump = m_WaterMove.FindAction("Jump", throwIfNotFound: true);
        m_WaterMove_Move = m_WaterMove.FindAction("Move", throwIfNotFound: true);
        m_WaterMove_MoveCursor = m_WaterMove.FindAction("MoveCursor", throwIfNotFound: true);
        m_WaterMove_Lockon = m_WaterMove.FindAction("Lockon", throwIfNotFound: true);
        m_WaterMove_Throttle = m_WaterMove.FindAction("Throttle", throwIfNotFound: true);
        // LedgeGrab
        m_LedgeGrab = asset.FindActionMap("LedgeGrab", throwIfNotFound: true);
        m_LedgeGrab_Jump = m_LedgeGrab.FindAction("Jump", throwIfNotFound: true);
        m_LedgeGrab_Move = m_LedgeGrab.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GroundMove
    private readonly InputActionMap m_GroundMove;
    private IGroundMoveActions m_GroundMoveActionsCallbackInterface;
    private readonly InputAction m_GroundMove_Move;
    private readonly InputAction m_GroundMove_Rotate;
    private readonly InputAction m_GroundMove_Jump;
    private readonly InputAction m_GroundMove_DashJump;
    private readonly InputAction m_GroundMove_Dash;
    private readonly InputAction m_GroundMove_L1;
    private readonly InputAction m_GroundMove_R1;
    private readonly InputAction m_GroundMove_MoveCursor;
    private readonly InputAction m_GroundMove_Lockon;
    private readonly InputAction m_GroundMove_Sword;
    private readonly InputAction m_GroundMove_Attack;
    private readonly InputAction m_GroundMove_Aim;
    public struct GroundMoveActions
    {
        private @PlayerControls m_Wrapper;
        public GroundMoveActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_GroundMove_Move;
        public InputAction @Rotate => m_Wrapper.m_GroundMove_Rotate;
        public InputAction @Jump => m_Wrapper.m_GroundMove_Jump;
        public InputAction @DashJump => m_Wrapper.m_GroundMove_DashJump;
        public InputAction @Dash => m_Wrapper.m_GroundMove_Dash;
        public InputAction @L1 => m_Wrapper.m_GroundMove_L1;
        public InputAction @R1 => m_Wrapper.m_GroundMove_R1;
        public InputAction @MoveCursor => m_Wrapper.m_GroundMove_MoveCursor;
        public InputAction @Lockon => m_Wrapper.m_GroundMove_Lockon;
        public InputAction @Sword => m_Wrapper.m_GroundMove_Sword;
        public InputAction @Attack => m_Wrapper.m_GroundMove_Attack;
        public InputAction @Aim => m_Wrapper.m_GroundMove_Aim;
        public InputActionMap Get() { return m_Wrapper.m_GroundMove; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GroundMoveActions set) { return set.Get(); }
        public void SetCallbacks(IGroundMoveActions instance)
        {
            if (m_Wrapper.m_GroundMoveActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnMove;
                @Rotate.started -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnRotate;
                @Rotate.performed -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnRotate;
                @Rotate.canceled -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnRotate;
                @Jump.started -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnJump;
                @DashJump.started -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnDashJump;
                @DashJump.performed -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnDashJump;
                @DashJump.canceled -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnDashJump;
                @Dash.started -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnDash;
                @L1.started -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnL1;
                @L1.performed -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnL1;
                @L1.canceled -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnL1;
                @R1.started -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnR1;
                @R1.performed -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnR1;
                @R1.canceled -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnR1;
                @MoveCursor.started -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnMoveCursor;
                @MoveCursor.performed -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnMoveCursor;
                @MoveCursor.canceled -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnMoveCursor;
                @Lockon.started -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnLockon;
                @Lockon.performed -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnLockon;
                @Lockon.canceled -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnLockon;
                @Sword.started -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnSword;
                @Sword.performed -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnSword;
                @Sword.canceled -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnSword;
                @Attack.started -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnAttack;
                @Aim.started -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnAim;
                @Aim.performed -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnAim;
                @Aim.canceled -= m_Wrapper.m_GroundMoveActionsCallbackInterface.OnAim;
            }
            m_Wrapper.m_GroundMoveActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Rotate.started += instance.OnRotate;
                @Rotate.performed += instance.OnRotate;
                @Rotate.canceled += instance.OnRotate;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @DashJump.started += instance.OnDashJump;
                @DashJump.performed += instance.OnDashJump;
                @DashJump.canceled += instance.OnDashJump;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @L1.started += instance.OnL1;
                @L1.performed += instance.OnL1;
                @L1.canceled += instance.OnL1;
                @R1.started += instance.OnR1;
                @R1.performed += instance.OnR1;
                @R1.canceled += instance.OnR1;
                @MoveCursor.started += instance.OnMoveCursor;
                @MoveCursor.performed += instance.OnMoveCursor;
                @MoveCursor.canceled += instance.OnMoveCursor;
                @Lockon.started += instance.OnLockon;
                @Lockon.performed += instance.OnLockon;
                @Lockon.canceled += instance.OnLockon;
                @Sword.started += instance.OnSword;
                @Sword.performed += instance.OnSword;
                @Sword.canceled += instance.OnSword;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Aim.started += instance.OnAim;
                @Aim.performed += instance.OnAim;
                @Aim.canceled += instance.OnAim;
            }
        }
    }
    public GroundMoveActions @GroundMove => new GroundMoveActions(this);

    // WaterMove
    private readonly InputActionMap m_WaterMove;
    private IWaterMoveActions m_WaterMoveActionsCallbackInterface;
    private readonly InputAction m_WaterMove_Turn;
    private readonly InputAction m_WaterMove_Rotate;
    private readonly InputAction m_WaterMove_Accelerate;
    private readonly InputAction m_WaterMove_Rise;
    private readonly InputAction m_WaterMove_Fall;
    private readonly InputAction m_WaterMove_Boost;
    private readonly InputAction m_WaterMove_Attack;
    private readonly InputAction m_WaterMove_Jump;
    private readonly InputAction m_WaterMove_Move;
    private readonly InputAction m_WaterMove_MoveCursor;
    private readonly InputAction m_WaterMove_Lockon;
    private readonly InputAction m_WaterMove_Throttle;
    public struct WaterMoveActions
    {
        private @PlayerControls m_Wrapper;
        public WaterMoveActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Turn => m_Wrapper.m_WaterMove_Turn;
        public InputAction @Rotate => m_Wrapper.m_WaterMove_Rotate;
        public InputAction @Accelerate => m_Wrapper.m_WaterMove_Accelerate;
        public InputAction @Rise => m_Wrapper.m_WaterMove_Rise;
        public InputAction @Fall => m_Wrapper.m_WaterMove_Fall;
        public InputAction @Boost => m_Wrapper.m_WaterMove_Boost;
        public InputAction @Attack => m_Wrapper.m_WaterMove_Attack;
        public InputAction @Jump => m_Wrapper.m_WaterMove_Jump;
        public InputAction @Move => m_Wrapper.m_WaterMove_Move;
        public InputAction @MoveCursor => m_Wrapper.m_WaterMove_MoveCursor;
        public InputAction @Lockon => m_Wrapper.m_WaterMove_Lockon;
        public InputAction @Throttle => m_Wrapper.m_WaterMove_Throttle;
        public InputActionMap Get() { return m_Wrapper.m_WaterMove; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WaterMoveActions set) { return set.Get(); }
        public void SetCallbacks(IWaterMoveActions instance)
        {
            if (m_Wrapper.m_WaterMoveActionsCallbackInterface != null)
            {
                @Turn.started -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnTurn;
                @Turn.performed -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnTurn;
                @Turn.canceled -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnTurn;
                @Rotate.started -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnRotate;
                @Rotate.performed -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnRotate;
                @Rotate.canceled -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnRotate;
                @Accelerate.started -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnAccelerate;
                @Accelerate.performed -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnAccelerate;
                @Accelerate.canceled -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnAccelerate;
                @Rise.started -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnRise;
                @Rise.performed -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnRise;
                @Rise.canceled -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnRise;
                @Fall.started -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnFall;
                @Fall.performed -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnFall;
                @Fall.canceled -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnFall;
                @Boost.started -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnBoost;
                @Boost.performed -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnBoost;
                @Boost.canceled -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnBoost;
                @Attack.started -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnAttack;
                @Jump.started -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnJump;
                @Move.started -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnMove;
                @MoveCursor.started -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnMoveCursor;
                @MoveCursor.performed -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnMoveCursor;
                @MoveCursor.canceled -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnMoveCursor;
                @Lockon.started -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnLockon;
                @Lockon.performed -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnLockon;
                @Lockon.canceled -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnLockon;
                @Throttle.started -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnThrottle;
                @Throttle.performed -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnThrottle;
                @Throttle.canceled -= m_Wrapper.m_WaterMoveActionsCallbackInterface.OnThrottle;
            }
            m_Wrapper.m_WaterMoveActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Turn.started += instance.OnTurn;
                @Turn.performed += instance.OnTurn;
                @Turn.canceled += instance.OnTurn;
                @Rotate.started += instance.OnRotate;
                @Rotate.performed += instance.OnRotate;
                @Rotate.canceled += instance.OnRotate;
                @Accelerate.started += instance.OnAccelerate;
                @Accelerate.performed += instance.OnAccelerate;
                @Accelerate.canceled += instance.OnAccelerate;
                @Rise.started += instance.OnRise;
                @Rise.performed += instance.OnRise;
                @Rise.canceled += instance.OnRise;
                @Fall.started += instance.OnFall;
                @Fall.performed += instance.OnFall;
                @Fall.canceled += instance.OnFall;
                @Boost.started += instance.OnBoost;
                @Boost.performed += instance.OnBoost;
                @Boost.canceled += instance.OnBoost;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @MoveCursor.started += instance.OnMoveCursor;
                @MoveCursor.performed += instance.OnMoveCursor;
                @MoveCursor.canceled += instance.OnMoveCursor;
                @Lockon.started += instance.OnLockon;
                @Lockon.performed += instance.OnLockon;
                @Lockon.canceled += instance.OnLockon;
                @Throttle.started += instance.OnThrottle;
                @Throttle.performed += instance.OnThrottle;
                @Throttle.canceled += instance.OnThrottle;
            }
        }
    }
    public WaterMoveActions @WaterMove => new WaterMoveActions(this);

    // LedgeGrab
    private readonly InputActionMap m_LedgeGrab;
    private ILedgeGrabActions m_LedgeGrabActionsCallbackInterface;
    private readonly InputAction m_LedgeGrab_Jump;
    private readonly InputAction m_LedgeGrab_Move;
    public struct LedgeGrabActions
    {
        private @PlayerControls m_Wrapper;
        public LedgeGrabActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_LedgeGrab_Jump;
        public InputAction @Move => m_Wrapper.m_LedgeGrab_Move;
        public InputActionMap Get() { return m_Wrapper.m_LedgeGrab; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LedgeGrabActions set) { return set.Get(); }
        public void SetCallbacks(ILedgeGrabActions instance)
        {
            if (m_Wrapper.m_LedgeGrabActionsCallbackInterface != null)
            {
                @Jump.started -= m_Wrapper.m_LedgeGrabActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_LedgeGrabActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_LedgeGrabActionsCallbackInterface.OnJump;
                @Move.started -= m_Wrapper.m_LedgeGrabActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_LedgeGrabActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_LedgeGrabActionsCallbackInterface.OnMove;
            }
            m_Wrapper.m_LedgeGrabActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
            }
        }
    }
    public LedgeGrabActions @LedgeGrab => new LedgeGrabActions(this);
    public interface IGroundMoveActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnDashJump(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnL1(InputAction.CallbackContext context);
        void OnR1(InputAction.CallbackContext context);
        void OnMoveCursor(InputAction.CallbackContext context);
        void OnLockon(InputAction.CallbackContext context);
        void OnSword(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
    }
    public interface IWaterMoveActions
    {
        void OnTurn(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnAccelerate(InputAction.CallbackContext context);
        void OnRise(InputAction.CallbackContext context);
        void OnFall(InputAction.CallbackContext context);
        void OnBoost(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnMoveCursor(InputAction.CallbackContext context);
        void OnLockon(InputAction.CallbackContext context);
        void OnThrottle(InputAction.CallbackContext context);
    }
    public interface ILedgeGrabActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
    }
}
